{
    "name": "Instance Creator",
    "summary": """
    Instance creator for typ, this is the app.
    """,
    "author": "Vauxoo",
    "website": "http://www.vauxoo.com",
    "license": "LGPL-3",
    "category": "Installer",
    "version": "14.0.1.0.0",
    "depends": [
        "account_budget",
        # "account_check_printing",
        "account_payment",
        "account_reports_cash_basis",
        "auth_oauth",
        "barcodes_generator_product",
        "base_report_to_printer",
        "crm",
        "delivery",
        "fleet",
        "helpdesk",
        "hr_payroll",
        "l10n_mx_edi_customs_diot",
        "l10n_mx_edi_extended",
        "l10n_mx_edi_hr_expense",
        "l10n_mx_edi_partner_defaults",
        "mrp",
        "note",
        "point_of_sale",
        "product_supplierinfo_for_customer_sale",
        "purchase_requisition",
        "sale_credit_management",
        "sale_margin",
        "stock_landed_costs",
        "stock_picking_show_return",
        "default_warehouse_from_sale_team",
        "website_blog",
        "website_sale",
        "website_sale_delivery",
    ],
    "data": [
        # Data
        "data/account_payment_term_data.xml",
        "data/hr_employee_check_data.xml",
        "data/ir_sequence_data.xml",
        "data/product_pricelist_data.xml",
        "data/product_public_category_data.xml",
        "data/report_paperformat_data.xml",
        "data/res_company_data.xml",
        "data/res_partner_category_data.xml",
        "data/settings.xml",
        "data/website_settings.xml",
        # Security
        "security/typ_security.xml",
        "security/ir.model.access.csv",
        # Menus
        "views/menuitems.xml",
        # Reports
        "reports/account_report_payment_receipt_templates.xml",
        "reports/layout.xml",
        "reports/purchase_order.xml",
        "reports/hr_employee_indicator_views.xml",
        "reports/hr_employee_report_views.xml",
        "reports/purchase_quotation.xml",
        "reports/report_invoice.xml",
        "reports/report_sale_order.xml",
        "reports/report_stockpicking_wobc.xml",
        "reports/report_stockpicking.xml",
        "reports/report_stock_views.xml",
        "reports/sale_order_report.xml",
        "reports/stock_report_deliveryslip.xml",
        # Wizards
        "wizards/invoice_from_guides_views.xml",
        "wizards/stock_product_print_label_views.xml",
        "wizards/stock_scheduler_compute_views.xml",
        # Views
        "views/account_journal_views.xml",
        "views/account_move_views.xml",
        "views/account_payment_views.xml",
        "views/assets.xml",
        "views/crm_lead_views.xml",
        "views/crm_team_views.xml",
        "views/fleet_vehicle_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_employee_auxiliar_views.xml",
        "views/hr_employee_beneficiary_views.xml",
        "views/hr_employee_reference_views.xml",
        "views/hr_employee_views.xml",
        "views/layout.xml",
        "views/product_category_views.xml",
        "views/product_market_type_views.xml",
        "views/product_pricelist_item_views.xml",
        "views/product_pricelist_views.xml",
        "views/product_product_views.xml",
        "views/product_public_category_views.xml",
        "views/product_template_views.xml",
        "views/purchase_order_views.xml",
        "views/purchase_requisition_views.xml",
        "views/res_company_views.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "views/stock_inventory_views.xml",
        "views/stock_landed_cost_guide_views.xml",
        "views/stock_landed_cost_views.xml",
        "views/stock_location_route_views.xml",
        "views/stock_location_views.xml",
        "views/stock_manual_transfer_views.xml",
        "views/stock_move_line_views.xml",
        "views/stock_move_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_warehouse_orderpoint_views.xml",
        "views/templates.xml",
        # Pages
        "views/pages/about.xml",
        "views/pages/account.xml",
        "views/pages/catalog.xml",
        "views/pages/contact.xml",
        "views/pages/loyalty.xml",
        "views/pages/organizations.xml",
        "views/pages/pdp.xml",
        "views/pages/providers.xml",
        "views/pages/shop.xml",
        "views/pages/snippets.xml",
    ],
    "demo": [
        "demo/crm_team_demo.xml",
        "demo/product_demo.xml",
        "demo/res_partner_demo.xml",
        "demo/stock_demo.xml",
    ],
    "qweb": [],
    "installable": True,
    "application": True,
}
