from . import account_journal
from . import account_move
from . import account_move_line
from . import account_payment
from . import crm_lead
from . import crm_team
from . import fleet_vehicle
from . import helpdesk_ticket
from . import hr_contract
from . import hr_employee
from . import hr_employee_auxiliar
from . import hr_employee_base
from . import hr_employee_beneficiary
from . import hr_employee_check
from . import hr_employee_public
from . import hr_employee_reference
from . import __init__
from . import pos_order
from . import procurement_group
from . import product_category
from . import product_market_type
from . import product_pricelist
from . import product_pricelist_item
from . import product_product
from . import product_public_category
from . import product_stock_warehouse
from . import product_template
from . import purchase_order
from . import purchase_order_line
from . import res_company
from . import res_config_settings
from . import res_country
from . import res_partner
from . import res_partner_warehouse
from . import sale_order
from . import sale_order_line
from . import stock_landed_cost
from . import stock_landed_cost_guide
from . import stock_location
from . import stock_location_route
from . import stock_manual_transfer
from . import stock_move
from . import stock_move_line
from . import stock_picking
from . import stock_picking_type
from . import stock_quant
from . import stock_rule
from . import stock_scrap
from . import stock_warehouse
from . import stock_warehouse_orderpoint
from . import user_wishlist
from . import website
