from . import account_move
from . import account_move_line
from . import account_payment
from . import fleet_vehicle
from . import res_partner
from . import res_partner_warehouse
from . import product_public_category
from . import product_category
from . import product_market_type
from . import product
from . import res_country
from . import user_wishlist
from . import stock_move_line
from . import pos_order
from . import helpdesk_ticket
from . import sale_order_line
from . import sale_order
from . import crm_lead
from . import res_config
from . import res_company
from . import purchase_order
from . import sales_team
from . import pricelist
from . import product_stock_warehouse
from . import hr_employee
from . import hr_contract
from . import hr_employee_beneficiary
from . import hr_employee_auxiliar
from . import hr_employee_reference
from . import hr_employee_check
from . import hr_sed
