image: vauxoo/odoo-80-image-shippable-auto
stages:
  - test
  - test_build
  - build

lint:
  stage: test
  tags:
    - lint
  variables:
    LINT_CHECK: "1"
    TESTS: "0"
  script:
    - source variables.sh
    - export TRAVIS_BUILD_DIR=$(pwd)
    - pip install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate
    - source ${REPO_REQUIREMENTS}/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
    - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
      # Disable file-not-used because is the project in process of migration: Remove this line after migrate the xml files
    - sed -i "/file-not-used/d" ${HOME}/maintainer-quality-tools/travis/cfg/travis_run_pylint_pr.cfg
    - travis_run_tests

test:
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  tags:
    - odoo
    - test
  variables:
    LINT_CHECK: "0"
    TESTS: "1"
  script:
    - source variables.sh
    - export TRAVIS_BUILD_DIR=$(pwd)
    - pip install deployv-addon-gitlab-tools
    - apt-get update
    - apt-get install python3-dev python3-dev libcups2-dev gcc
    - deployvcmd gitlab_tools check_keys
    - source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate
    - source ${REPO_REQUIREMENTS}/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
    - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true
    - coverage html --rcfile=${TRAVIS_BUILD_DIR}/.coveragerc -d $CI_COMMIT_REF_SLUG
    - coverage report -m --show-missing --rcfile=${TRAVIS_BUILD_DIR}/.coveragerc || true
  artifacts:
    paths:
      - $CI_COMMIT_REF_SLUG

publish_coverage:
  image: quay.io/vauxoo/dockerv:latest
  stage: test_build
  dependencies:
    - test
  script:
    - source variables.sh
    - deployvcmd gitlab_tools push_coverage
  environment:
    name: coverage
    url: https://coverage.vauxoo.com/${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}

build:
  stage: build
  image: quay.io/vauxoo/dockerv:latest
  tags:
    - build
  script:
    - source variables.sh
    - deployvcmd gitlab_tools check_keys
    - deployvcmd gitlab_tools test_images --push_image
