image: vauxoo/odoo-80-image-shippable-auto
stages:
  - test
  - test_build
  - build
  - upload_image

variables:
    PSQL_VERSION: "9.6"
    VERSION: "11.0"
    TRAVIS_PYTHON_VERSION: "3.5"
    ODOO_REPO: "vauxoo/odoo"
    ODOO_BRANCH: "11.0"
    BASE_IMAGE: "vauxoo/odoo-110-image"
    COUNTRY: "MX"
    TEST_OTHER_PROJECTS: "${TRAVIS_BUILD_DIR}/addons-vauxoo"

lint:
  stage: test
  tags:
    - lint
  variables:
    LINT_CHECK: "1"
    TESTS: "0"
  script:
    - export TRAVIS_BUILD_DIR=$(pwd)
    - pip install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate
    - source ${REPO_REQUIREMENTS}/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
    - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
    - travis_run_tests

test:
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  tags:
    - odoo
    - test
  variables:
    LINT_CHECK: "0"
    TESTS: "1"
    INCLUDE: "typ"
    INSTALL: "typ"
  script:
    - export TRAVIS_BUILD_DIR=$(pwd)
    - pip install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate
    - source ${REPO_REQUIREMENTS}/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/activate
    - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true
    - coverage report -m --show-missing --rcfile=${TRAVIS_BUILD_DIR}/.coveragerc || true
  artifacts:
    paths:
      - $CI_COMMIT_REF_SLUG

publish_coverage:
  image: quay.io/vauxoo/dockerv:latest
  stage: test_build
  dependencies:
    - test
  script:
    - deployvcmd gitlab_tools push_coverage
  environment:
    name: coverage
    url: https://coverage.vauxoo.com/${CI_COMMIT_REF_SLUG}-${CI_PROJECT_NAME}

build:
  stage: build
  image: quay.io/vauxoo/dockerv:latest
  tags:
    - build
  variables:
    INSTALL: "typ"
    CUSTOMER: "typ"
  script:
    - deployvcmd gitlab_tools check_keys
    - deployvcmd gitlab_tools test_images --push_image

upload_image:
  stage: upload_image
  only:
      - 8.0@vauxoo/typ
  when: on_success
  tags:
    - build
  variables:
    CUSTOMER: "typ"
  script:
    - deployvcmd gitlab_tools upload_image
