language: python

sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  postgresql: "9.6"

addons:
  apt:
    packages:
      - expect-dev
      - python-lxml
      - python-simplejson
      - python-yaml
      - swig  # Required for m2crypto
      - python-m2crypto
      - xmlstarlet
      - xsltproc
      - openssl
      - poppler-utils
      - antiword
      - cups
      - libcups2-dev
python:
  - "3.5"

env:
  global:
  - LINT_CHECK="0" TESTS="0"
  matrix:
  - LINT_CHECK="1"
  - INCLUDE="typ" TESTS="1"

install:
  - source ${TRAVIS_BUILD_DIR}/variables.sh
  - git clone --single-branch --depth=1 https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - source ${TRAVIS_BUILD_DIR}/variables.sh
  - travis_run_tests

after_success:
  - source ${TRAVIS_BUILD_DIR}/variables.sh
  - travis_after_tests_success
