{
    "name": "TYP POS",
    "summary": "Display Stocks inside POS. Allow/Deny" " Order based on stocks.",
    "category": "Point Of Sale",
    "version": "14.0.1.0.0",
    "sequence": 1,
    "author": "Webkul Software Pvt. Ltd., Vauxoo",
    "website": "https://store.webkul.com/Odoo-POS-Stock.html",
    "license": "Other proprietary",
    "live_test_url": "http://odoodemo.webkul.com/?module=" "pos_stocks&version=10.0",
    "depends": ["point_of_sale"],
    "data": [
        "report/receipt_report.xml",
        "data/res_groups.xml",
        # "views/pos_stocks_view.xml",
        "views/template.xml",
        "views/pos_view.xml",
        "views/point_of_sale_report.xml",
        "security/ir.model.access.csv",
    ],
    "qweb": [
        "static/src/xml/pos_stocks.xml",
        "static/src/xml/pos.xml",
    ],
    "installable": False,
    "auto_install": False,
    "post_init_hook": "_set_new_group",
}
